NgRx
laska-sl/arcadia-parties pull request #29
Opened 2020-02-20 17:15 UTC by Duveshka

2020-02-20 18:18 UTC, sponkrashin commented on ArcadiaParties-SPA/src/app/app.effects.spec.ts
> +import { provideMockActions } from '@ngrx/effects/testing';
That's great, but we could skip testing for this project. Otherwise you can to not meet deadlines.

2020-02-20 18:19 UTC, sponkrashin commented on ArcadiaParties-SPA/src/app/app.module.ts
> +import { StoreModule } from '@ngrx/store';
Good practice is to place all local imports after all external ones, separated with empty line.

2020-02-20 20:20 UTC, sponkrashin requested changes
Remove calendar and register action, reducers and etc. They should not be added in main state, it is a responsibility of feature state modules.

2020-02-20 20:20 UTC, sponkrashin commented on ArcadiaParties-SPA/src/app/reducers/index.ts
> +export const metaReducers: MetaReducer<State>[] = !environment.production ? [] : [];
Do you understand what are meta reducers needed for? Probably, you won't need them in the project.
https://ngrx.io/guide/store/metareducers

2020-02-21 10:16 UTC, sponkrashin requested changes

2020-02-21 10:16 UTC, sponkrashin commented on ArcadiaParties-SPA/src/app/reducers/reducers.ts
> +import { headerFeatureStateKey, HeaderState, reducers } from './header-reducers';
Local imports after external ones.

2020-02-21 10:23 UTC, Duveshka commented on ArcadiaParties-SPA/src/app/reducers/reducers.ts
> +import { headerFeatureStateKey, HeaderState, reducers } from './header-reducers';
I've fixed it

2020-02-21 10:29 UTC, sponkrashin approved these changes

2020-02-21 10:32 UTC, merged